version: "3.4.0"

services:
  mysql:
    image: mysql:8
    container_name: mysql_db_docker
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    ports:
      - "3307:3306"

    volumes:
      - ./mysql_data:/var/lib/mysql

  springboot:
    build: .
    environment:
      SERVER_PORT: 8080
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: quizapp
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_USERNAME: nileshbakade786@gmail.com
      EMAIL_PASSWORD: cvpjhsjidjqythvm
    ports:
      - "8082:8080"
    depends_on:
      - mysql
volumes:
  mysql_data: